env:
  es6: true
  browser: true
  commonjs: true
  jest: true

parser: '@typescript-eslint/parser',
extends: [
  'htmlacademy/es6',
  'plugin:react/recommended',
  'plugin:@typescript-eslint/recommended'
  ]

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 6
  sourceType: module

plugins: [
  '@typescript-eslint',
  'react-hooks',
  'react'
]

settings:
  react:
    version: '16',
    pragma: React,

 rules: {
    'react-hooks/rules-of-hooks': error,
    'react-hooks/exhaustive-deps': warn,
    'react/prop-types': off
  },
